/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeccoesRouteImport } from './routes/seccoes'
import { Route as RepositorioRouteImport } from './routes/repositorio'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeccoesIndexRouteImport } from './routes/seccoes.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as SeccoesSlugRouteImport } from './routes/seccoes.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUtilizadoresRouteImport } from './routes/_authenticated/admin.utilizadores'
import { Route as AuthenticatedAdminSeccoesRouteImport } from './routes/_authenticated/admin.seccoes'
import { Route as AuthenticatedAdminRepositorioRouteImport } from './routes/_authenticated/admin.repositorio'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeccoesRoute = SeccoesRouteImport.update({
  id: '/seccoes',
  path: '/seccoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositorioRoute = RepositorioRouteImport.update({
  id: '/repositorio',
  path: '/repositorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeccoesIndexRoute = SeccoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeccoesRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const SeccoesSlugRoute = SeccoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeccoesRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventosRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUtilizadoresRoute =
  AuthenticatedAdminUtilizadoresRouteImport.update({
    id: '/utilizadores',
    path: '/utilizadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeccoesRoute =
  AuthenticatedAdminSeccoesRouteImport.update({
    id: '/seccoes',
    path: '/seccoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRepositorioRoute =
  AuthenticatedAdminRepositorioRouteImport.update({
    id: '/repositorio',
    path: '/repositorio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contactos': typeof ContactosRoute
  '/eventos': typeof EventosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/repositorio': typeof RepositorioRoute
  '/seccoes': typeof SeccoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/seccoes/$slug': typeof SeccoesSlugRoute
  '/eventos/': typeof EventosIndexRoute
  '/seccoes/': typeof SeccoesIndexRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/repositorio': typeof AuthenticatedAdminRepositorioRoute
  '/admin/seccoes': typeof AuthenticatedAdminSeccoesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contactos': typeof ContactosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repositorio': typeof RepositorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/seccoes/$slug': typeof SeccoesSlugRoute
  '/eventos': typeof EventosIndexRoute
  '/seccoes': typeof SeccoesIndexRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/repositorio': typeof AuthenticatedAdminRepositorioRoute
  '/admin/seccoes': typeof AuthenticatedAdminSeccoesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/contactos': typeof ContactosRoute
  '/eventos': typeof EventosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/repositorio': typeof RepositorioRoute
  '/seccoes': typeof SeccoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/eventos/$slug': typeof EventosSlugRoute
  '/seccoes/$slug': typeof SeccoesSlugRoute
  '/eventos/': typeof EventosIndexRoute
  '/seccoes/': typeof SeccoesIndexRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/repositorio': typeof AuthenticatedAdminRepositorioRoute
  '/_authenticated/admin/seccoes': typeof AuthenticatedAdminSeccoesRoute
  '/_authenticated/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/contactos'
    | '/eventos'
    | '/privacidade'
    | '/repositorio'
    | '/seccoes'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/eventos/$slug'
    | '/seccoes/$slug'
    | '/eventos/'
    | '/seccoes/'
    | '/admin/eventos'
    | '/admin/repositorio'
    | '/admin/seccoes'
    | '/admin/utilizadores'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/contactos'
    | '/privacidade'
    | '/repositorio'
    | '/sitemap.xml'
    | '/termos'
    | '/eventos/$slug'
    | '/seccoes/$slug'
    | '/eventos'
    | '/seccoes'
    | '/admin/eventos'
    | '/admin/repositorio'
    | '/admin/seccoes'
    | '/admin/utilizadores'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendario'
    | '/contactos'
    | '/eventos'
    | '/privacidade'
    | '/repositorio'
    | '/seccoes'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/eventos/$slug'
    | '/seccoes/$slug'
    | '/eventos/'
    | '/seccoes/'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/repositorio'
    | '/_authenticated/admin/seccoes'
    | '/_authenticated/admin/utilizadores'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ContactosRoute: typeof ContactosRoute
  EventosRoute: typeof EventosRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RepositorioRoute: typeof RepositorioRoute
  SeccoesRoute: typeof SeccoesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seccoes': {
      id: '/seccoes'
      path: '/seccoes'
      fullPath: '/seccoes'
      preLoaderRoute: typeof SeccoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositorio': {
      id: '/repositorio'
      path: '/repositorio'
      fullPath: '/repositorio'
      preLoaderRoute: typeof RepositorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seccoes/': {
      id: '/seccoes/'
      path: '/'
      fullPath: '/seccoes/'
      preLoaderRoute: typeof SeccoesIndexRouteImport
      parentRoute: typeof SeccoesRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/seccoes/$slug': {
      id: '/seccoes/$slug'
      path: '/$slug'
      fullPath: '/seccoes/$slug'
      preLoaderRoute: typeof SeccoesSlugRouteImport
      parentRoute: typeof SeccoesRoute
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof EventosRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilizadores': {
      id: '/_authenticated/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seccoes': {
      id: '/_authenticated/admin/seccoes'
      path: '/seccoes'
      fullPath: '/admin/seccoes'
      preLoaderRoute: typeof AuthenticatedAdminSeccoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/repositorio': {
      id: '/_authenticated/admin/repositorio'
      path: '/repositorio'
      fullPath: '/admin/repositorio'
      preLoaderRoute: typeof AuthenticatedAdminRepositorioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminRepositorioRoute: typeof AuthenticatedAdminRepositorioRoute
  AuthenticatedAdminSeccoesRoute: typeof AuthenticatedAdminSeccoesRoute
  AuthenticatedAdminUtilizadoresRoute: typeof AuthenticatedAdminUtilizadoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminRepositorioRoute: AuthenticatedAdminRepositorioRoute,
  AuthenticatedAdminSeccoesRoute: AuthenticatedAdminSeccoesRoute,
  AuthenticatedAdminUtilizadoresRoute: AuthenticatedAdminUtilizadoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventosRouteChildren {
  EventosSlugRoute: typeof EventosSlugRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosSlugRoute: EventosSlugRoute,
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface SeccoesRouteChildren {
  SeccoesSlugRoute: typeof SeccoesSlugRoute
  SeccoesIndexRoute: typeof SeccoesIndexRoute
}

const SeccoesRouteChildren: SeccoesRouteChildren = {
  SeccoesSlugRoute: SeccoesSlugRoute,
  SeccoesIndexRoute: SeccoesIndexRoute,
}

const SeccoesRouteWithChildren =
  SeccoesRoute._addFileChildren(SeccoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ContactosRoute: ContactosRoute,
  EventosRoute: EventosRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RepositorioRoute: RepositorioRoute,
  SeccoesRoute: SeccoesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
